api/urls.py
from django.urls import path

from .views import (
    CategoryListAPIView,
    VideoListAPIView,
    CategoryDetailAPIView,
    VideoDetailAPIView,
    BaseAPIView,
)

app_name = 'api'
urlpatterns = [
    path('', BaseAPIView.as_view(), name='base_api'),
    path('category/<int:id>/', CategoryDetailAPIView.as_view(), name='category_api'),
    path('categories/', CategoryListAPIView.as_view(), name='categories_api'),
    path('video/<int:id>/', VideoDetailAPIView.as_view(), name='video_api'),
    path('videos/', VideoListAPIView.as_view(), name='videos_api'),
]

django_video_hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('authorisation_user.urls')),
    path('comments/', include('comments.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models

# Create your models here.

api/views.py
from django.shortcuts import render
from django.views import View

from rest_framework.generics import ListAPIView, RetrieveAPIView
from rest_framework.pagination import PageNumberPagination

from .serializers import CategorySerializer, VideoSerializer
from main.models import Category, Video


class BaseAPIView(View):
    """ API navigations """

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        videos = Video.objects.filter(blocked=False, private=False)
        context = {'categories': categories, 'videos': videos}
        return render(request, 'api/base_api.html', context)


class Pagination(PageNumberPagination):
    """ Pagination """

    page_size = 2
    page_size_query_param = 'page_size'
    max_page_size = 10


class CategoryListAPIView(ListAPIView):
    """ List category """

    serializer_class = CategorySerializer
    pagination_class = Pagination
    queryset = Category.objects.all()


class VideoListAPIView(ListAPIView):
    """ List videos """

    serializer_class = VideoSerializer
    pagination_class = Pagination
    queryset = Video.objects.filter(blocked=False, private=False)


class CategoryDetailAPIView(RetrieveAPIView):
    """ Category Detail """

    serializer_class = CategorySerializer
    queryset = Category.objects.all()
    lookup_field = 'id'


class VideoDetailAPIView(RetrieveAPIView):
    """ Video Detail """

    serializer_class = VideoSerializer
    queryset = Video.objects.filter(blocked=False, private=False)
    lookup_field = 'id'

api/templates/api/base_api.html
{% extends 'base.html' %}

{% block title %}API{% endblock title %}

{% block content %}
    <div class="row">
        <h1 class="text-center">API</h1>
        <div class="col">
            <h3 class="text-center">All entries:</h3>
            <p><a class="btn btn-primary" href="{% url 'api:categories_api' %}">Categories</a></p>
            <p><a class="btn btn-primary" href="{% url 'api:videos_api' %}">Videos</a></p>
        </div>
        <div class="col">
            <h3 class="text-center">Categories:</h3>
            {% for category in categories %}
                <a class="btn btn-outline-primary" href="{% url 'api:category_api' id=category.id %}">
                    {{ category.name }}
                </a>
            {% endfor %}
        </div>
        <div class="col">
            <h3 class="text-center">Videos:</h3>
            {% for video in videos %}
                <a class="btn btn-outline-primary" href="{% url 'api:video_api' id=video.id %}">
                    {{ video.title }}
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}