api/urls.py
from django.urls import path

from .views import (
    CategoryListAPIView,
    VideoListAPIView,
    CategoryDetailAPIView,
    VideoDetailAPIView,
    BaseAPIView,
)

app_name = 'api'
urlpatterns = [
    path('', BaseAPIView.as_view(), name='base_api'),
    path('category/<int:id>/', CategoryDetailAPIView.as_view(), name='category_api'),
    path('categories/', CategoryListAPIView.as_view(), name='categories_api'),
    path('video/<int:id>/', VideoDetailAPIView.as_view(), name='video_api'),
    path('videos/', VideoListAPIView.as_view(), name='videos_api'),
]

authorisation_user/urls.py
from django.urls import path

from .views import (
    RegistrationView,
    LoginUserView,
    LogoutUserView,
    ProfileView,
    FollowAndUnfollowView,
    SubscriptionsView,
    ChangeProfileView,
    ChangePasswordView,
    RedirectProfileView,
    UserPopupView,
    HistoryView,
    DeleteVideoFromHistoryView,
    ResetPasswordView,
    ResetPasswordConfirmView,
    ActivationView,
    SendMailAboutActivationView,
)

app_name = 'accounts'
urlpatterns = [
    path('activation/send-mail/again/', SendMailAboutActivationView.as_view(), name='send_mail_about_activation'),
    path('activation/<str:username>/', ActivationView.as_view(), name='activate'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('profile/', RedirectProfileView.as_view(), name='profile_redirect'),
    path('profile/reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/reset/', ResetPasswordView.as_view(), name='reset_password'),
    path('profile/change/password/', ChangePasswordView.as_view(), name='password_change'),
    path('profile/change/', ChangeProfileView.as_view(), name='profile_change'),
    path('profile/<str:username>/popup/', UserPopupView.as_view(), name='user_popup'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('profile/<str:act>/<str:username>/', FollowAndUnfollowView.as_view(), name='act_profile'),
    path('subscriptions/', SubscriptionsView.as_view(), name='subscriptions'),
    path('history/delete/<str:slug>/', DeleteVideoFromHistoryView.as_view(), name='delete_from_history'),
    path('history/', HistoryView.as_view(), name='history'),
]

django_video_hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('authorisation_user.urls')),
    path('comments/', include('comments.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authorisation_user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

from main.utilities import get_timestamp_path


class AdvUser(AbstractUser):
    """ User """

    activated = models.BooleanField(default=False, verbose_name='User activated?')
    send_messages = models.BooleanField(default=True, verbose_name='Send notification about new comments?')
    subscription = models.ManyToManyField('AdvUser', verbose_name='Subscriptions', blank=True,
                                          related_name='subscriptions')
    subscriber = models.ManyToManyField('AdvUser', verbose_name='Subscribers', blank=True,
                                        related_name='subscribers')
    avatar = models.ImageField(verbose_name='Avatar', upload_to=get_timestamp_path)
    about = models.CharField(max_length=255, verbose_name='About me', blank=True, null=True)
    history = models.ManyToManyField('main.Video', verbose_name='History', blank=True)

    def follow(self, user):
        """ Follow """

        if not self.is_following(user):
            self.subscriptions.add(user)
            user.subscribers.add(self)

    def unfollow(self, user):
        """ Unfollow """

        if self.is_following(user):
            self.subscriptions.remove(user)
            user.subscribers.remove(self)

    def is_following(self, user):
        """ Is following user """

        return self.subscriptions.filter(username=user.username).count() > 0

    def get_absolute_url(self):
        """ Get absolute url """

        return reverse('accounts:profile', kwargs={'username': self.username})

    class Meta(AbstractUser.Meta):
        pass

authorisation_user/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .models import AdvUser


class RegistrationForm(forms.ModelForm):
    """ Registration User """

    email = forms.EmailField(required=True, label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput,
                               help_text=password_validation.password_validators_help_text_html())
    repeat_password = forms.CharField(label='Password (again)', widget=forms.PasswordInput, help_text='Password again')
    avatar = forms.FileField(widget=forms.FileInput)

    def clean_password(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password

    def clean_username(self):
        username = self.cleaned_data['username']
        if AdvUser.objects.filter(username=username).exists():
            raise ValidationError('Please use different username')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if AdvUser.objects.filter(email=email).exists():
            raise ValidationError('Please use a different email')
        return email

    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        repeat_password = self.cleaned_data['repeat_password']
        if password and repeat_password and password != repeat_password:
            errors = {'repeat_password': ValidationError('The passwords entered do not match', code='password_mismatch')}
            raise ValidationError(errors)

    class Meta:
        model = AdvUser
        fields = ('avatar', 'username', 'email', 'password', 'repeat_password', 'first_name', 'last_name',
                  'send_messages', 'about')


class ChangeProfileForm(forms.ModelForm):
    """ Profile change """

    email = forms.EmailField(required=True, label='Email')
    avatar = forms.FileField(widget=forms.FileInput)

    class Meta:
        model = AdvUser
        fields = ('avatar', 'username', 'email', 'first_name', 'last_name', 'send_messages', 'about')

authorisation_user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    PasswordChangeView,
    PasswordResetView,
    PasswordResetConfirmView,
)
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.shortcuts import render, redirect, Http404, get_object_or_404
from django.http import HttpResponseForbidden
from django.views import View

from .forms import RegistrationForm, ChangeProfileForm
from .models import AdvUser
from .send_mail import send_mail_about_activation
from .utils import get_count_all_views
from main.models import Video


class RedirectProfileView(View):
    """ Redirect after login """

    def get(self, request, *args, **kwargs):
        return redirect('accounts:profile', username=request.user.username)


class RegistrationView(View):
    """ Registration """

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('main:base')
        form = RegistrationForm(request.POST or None)
        context = {'form': form}
        return render(request, 'accounts/registration.html', context)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.username = form.cleaned_data['username']
            new_user.email = form.cleaned_data['email']
            new_user.first_name = form.cleaned_data['first_name']
            new_user.last_name = form.cleaned_data['last_name']
            new_user.send_messages = form.cleaned_data['send_messages']
            new_user.avatar = form.cleaned_data['avatar']
            new_user.about = form.cleaned_data['about']
            new_user.save()
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            user = authenticate(username=new_user.username, password=form.cleaned_data['password'])
            login(request, user)
            send_mail_about_activation(new_user)
            messages.add_message(request, messages.SUCCESS,
                                 'Success registration! Please activate your account, mail send')
            return redirect('accounts:profile', username=user.username)
        context = {'form': form}
        return render(request, 'accounts/registration.html', context)


class LoginUserView(SuccessMessageMixin, LoginView):
    """ Login """

    template_name = 'accounts/login.html'
    redirect_authenticated_user = True
    success_message = 'You are logged!'


class ChangeProfileView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """ Profile change """

    model = AdvUser
    template_name = 'accounts/profile_change.html'
    form_class = ChangeProfileForm
    success_message = 'Your profile has been changed!'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class ChangePasswordView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    """ Change Password User """

    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('main:base')
    success_message = 'Your password has been changed!'


class LogoutUserView(LoginRequiredMixin, View):
    """ Logout """

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'You are has been logout!')
        return redirect('main:base')


class ProfileView(View):
    """ Profile user """

    def get(self, request, *args, **kwargs):
        user = AdvUser.objects.filter(username=kwargs['username']).first()
        if not user:
            return Http404('Page not found')
        views = get_count_all_views(user)
        context = {'account': user, 'views': views}
        if request.user == user:
            context['statistic'] = get_count_all_views(user, True)
        return render(request, 'accounts/profile.html', context)


class FollowAndUnfollowView(LoginRequiredMixin, View):
    """ Follow and Unfollow """

    def get(self, request, *args, **kwargs):
        user = AdvUser.objects.filter(username=kwargs['username']).first()
        if not user:
            return Http404('Page not found')
        act = kwargs.get('act')
        if act == 'follow':
            request.user.follow(user)
            messages.add_message(request, messages.SUCCESS, 'You are has been follow!')
        elif act == 'unfollow':
            request.user.unfollow(user)
            messages.add_message(request, messages.SUCCESS, 'You are has been unfollow!')
        return redirect('accounts:profile', username=user.username)


class SubscriptionsView(LoginRequiredMixin, View):
    """ Subscriptions """

    def get(self, request, *args, **kwargs):
        subscriptions = request.user.subscriptions.all()
        context = {'subscriptions': subscriptions}
        return render(request, 'accounts/subscriptions.html', context)


class UserPopupView(View):
    """ User popup """

    def get(self, request, *args, **kwargs):
        user = AdvUser.objects.get(username=kwargs['username'])
        context = {'account': user}
        return render(request, 'accounts/user_popup.html', context)


class HistoryView(LoginRequiredMixin, View):
    """ History """

    def get(self, request, *args, **kwargs):
        return render(request, 'main/history.html')


class DeleteVideoFromHistoryView(LoginRequiredMixin, View):
    """ Delete video from history """

    def get(self, request, *args, **kwargs):
        video = Video.objects.get(slug=kwargs['slug'])
        request.user.history.remove(video)
        request.user.save()
        messages.add_message(request, messages.WARNING, 'You are deleted video from history!')
        return redirect('accounts:history')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    """ Reset password, email send """

    template_name = 'accounts/reset_password.html'
    subject_template_name = 'email/reset_subject.txt'
    email_template_name = 'email/reset_body.txt'
    success_url = reverse_lazy('main:base')
    success_message = 'Email sent!'


class ResetPasswordConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    """ Reset password """

    template_name = 'accounts/reset_password_confirm.html'
    success_url = reverse_lazy('main:base')
    success_message = 'Your password has been reset!'


class ActivationView(LoginRequiredMixin, View):
    """ Activation profile """

    def get(self, request, *args, **kwargs):
        user = AdvUser.objects.get(username=kwargs['username'])
        if request.user != user:
            raise HttpResponseForbidden('You cannot activate someone else\'s account!')
        user.activated = True
        user.save()
        messages.add_message(request, messages.SUCCESS, 'Your account has been activated!')
        return redirect('accounts:profile_redirect')


class SendMailAboutActivationView(LoginRequiredMixin, View):
    """ Send mail about activation if user deleted mail """

    def get(self, request, *args, **kwargs):
        if not request.user.activated:
            send_mail_about_activation(request.user)
        return redirect('accounts:profile_redirect')

authorisation_user/templates/accounts/change_password.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Change Password{% endblock title %}

{% block content %}
    <div class="row">
        <h1 class="text-center">Change password</h1>
        <form action="{% url 'accounts:password_change' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="mt-2 btn btn-success" value="Change password">
        </form>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
    <div class="row mb-5 pb-5">
        <h1 class="text-center">Login</h1>
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="mt-2 btn btn-success" value="Login">
            </form>
            <a class="mt-3 btn btn-primary" href="{% url 'accounts:registration' %}">Registration</a>
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/profile.html
{% extends 'base.html' %}

{% load follow_or_unfollow %}
{% load video %}

{% block title %}Profile - {{ account.username }}{% endblock title %}

{% block content %}
    <div class="row mb-5">
        <div class="col-8">
            <div class="row text-center mb-2">
                <div class="col">
                    <img class="img-200 img-fluid pb-2" src="{{ account.avatar.url }}" alt=""><br>
                    {% if account == user %}
                        <a href="{% url 'accounts:profile_change' %}"><button class="btn btn-primary">Change profile</button></a>
                    {% endif %}
                </div>
                <div class="col">
                    <span class="h1">{{ account.username.title }} videos
                        <span class="badge rounded-pill bg-secondary">{% if account != user %}{{ account.videos|filter_video_count }}{% else %}{{ account.videos.count }}{% endif %}</span><br>
                    </span>
                    {% if account.about %}
                        <p class="h5">{{ account.about }}</p>
                    {% endif %}
                    Views: <span class="badge rounded-pill bg-danger">{{ views }}</span>
                    {% if user == account %}<p>Statistic views (subscription views / views): <span class="strong">{{ statistic }}</span>%</p>{% endif %}
                </div>
            </div>
            <hr>
            <div class="row">
                {% if account == user %}
                    {% for video in account.videos.all %}
                        <div class="col-3">
                            {% include '_video_poster.html' %}
                        </div>
                    {% endfor %}
                {% else %}
                    {% filter_private_videos videos=account.videos.all as videos %}
                    {% for video in videos %}
                        <div class="col-3">
                            {% include '_video_poster.html' %}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="col-4">
            {% if account == user %}
                <h1 class="text-center">Subscriptions <span class="badge rounded-pill bg-secondary">{{ account.subscriptions.count }}</span></h1>
                <hr>
                {% for subscription in account.subscriptions.all %}
                    <div class="row text-center">
                        <div class="col">
                            <a href="{% url 'accounts:profile' username=subscription.username %}"><img class="img-80 img-fluid" src="{{ subscription.avatar.url }}" alt=""></a>
                        </div>
                        <div class="col">
                            <a href="{% url 'accounts:profile' username=subscription.username %}">{{ subscription.username.title }}</a><br>
                            Subscribers: <span class="badge rounded-pill bg-danger">{{ subscription.subscribers.count }}</span><br>
                            Videos: <span class="badge rounded-pill bg-secondary">{{ subscription.videos|filter_video_count }}</span>
                        </div>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                {% if user.is_authenticated %}
                    <h1 class="text-center">Subscribers <span class="badge rounded-pill bg-danger">{{ account.subscribers.count }}</span></h1>
                    <div class="row">
                        {% follow_or_unfollow account=account user=user as follow %}
                        {% if not follow %}
                            <a href="{% url 'accounts:act_profile' act='follow' username=account.username %}" class="btn btn-danger">Follow</a>
                        {% else %}
                            <a href="{% url 'accounts:act_profile' act='unfollow' username=account.username %}" class="btn btn-secondary">Unfollow</a>
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/profile_change.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Change profile{% endblock title %}

{% block content %}
    <div class="row mb-5">
        <h1 class="text-center">Change Profile</h1>
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'accounts:profile_change' %}" method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="mt-2 btn btn-success" value="Change">
            </form>
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/registration.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Registration{% endblock title %}

{% block content %}
    <div class="row mb-3">
        <h1 class="text-center">Registration</h1>
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'accounts:registration' %}" method="post" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success" value="Registration">
            </form>
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Reset password request{% endblock title %}

{% block content %}
    <div class="row">
        <h1 class="text-center">Request for reset password</h1>
        <div class="col-md-6 offset-md-3">
            <form action="{% url 'accounts:reset_password' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success mt-2" value="Send">
            </form>
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Reset password{% endblock title %}

{% block content %}
    <div class="row">
        <h1 class="text-center">Reset password</h1>
        <div class="col-md-6 offset-md-3">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success mt-2" value="Reset password">
            </form>
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/subscriptions.html
{% extends 'base.html' %}

{% block title %}Subscriptions{% endblock title %}

{% load video %}

{% block content %}
    <div class="row">
        <h1 class="text-center">Subscriptions:
            <span class="badge rounded-pill bg-secondary">{{ subscriptions.count }}</span></h1>
    </div>
    <div class="row mb-5">
        <div class="col-8">
            <div class="row">
                {% for subscription in subscriptions %}
                    {% filter_private_videos videos=subscription.videos.all as videos %}
                    {% for video in videos %}
                        <div class="col-3">
                            {% include '_video_poster.html' %}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
        <div class="col-4">
            <h3 class="text-center">Channels: <span class="badge rounded-pill bg-secondary">{{ subscriptions.count }}</span></h3>
            <hr>
            {% for subscription in subscriptions %}
                <div class="row text-center">
                    <div class="col">
                        <a href="{% url 'accounts:profile' username=subscription.username %}"><img
                                class="img-80 img-fluid" src="{{ subscription.avatar.url }}" alt=""></a>
                    </div>
                    <div class="col">
                        <a href="{% url 'accounts:profile' username=subscription.username %}">{{ subscription.username.title }}</a><br>
                        Subscribers: <span
                            class="badge rounded-pill bg-danger">{{ subscription.subscribers.count }}</span><br>
                        Videos: <span class="badge rounded-pill bg-secondary">{{ subscription.videos|filter_video_count }}</span>
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

authorisation_user/templates/accounts/user_popup.html
{% load follow_or_unfollow %}
<div class="row">
    <div class="col">
        <a href="{% url 'accounts:profile' username=account.username %}"><img class="img-80 img-fluid" src="{{ account.avatar.url }}" alt=""></a>
    </div>
    <div class="col">
        <a href="{% url 'accounts:profile' username=account.username %}">{{ account.username }}</a>
        {% if account.about %}<p>{{ account.about }}</p>{% endif %}
    </div>
    <div class="row">
        <p>Subscribers: <span class="badge rounded-pill bg-secondary">{{ account.subscribers.count }}</span></p>
        {% if user.is_authenticated %}
            {% if account != user %}
                {% follow_or_unfollow account=account user=user as follow %}
                {% if not follow %}
                    <a href="{% url 'accounts:act_profile' act='follow' username=account.username %}" class="btn btn-danger">Follow</a>
                {% else %}
                    <a href="{% url 'accounts:act_profile' act='unfollow' username=account.username %}" class="btn btn-secondary">Unfollow</a>
                {% endif %}
            {% endif %}
        {% endif %}
    </div>
</div>