api/urls.py
from django.urls import path

from .views import (
    CategoryListAPIView,
    VideoListAPIView,
    CategoryDetailAPIView,
    VideoDetailAPIView,
    BaseAPIView,
)

app_name = 'api'
urlpatterns = [
    path('', BaseAPIView.as_view(), name='base_api'),
    path('category/<int:id>/', CategoryDetailAPIView.as_view(), name='category_api'),
    path('categories/', CategoryListAPIView.as_view(), name='categories_api'),
    path('video/<int:id>/', VideoDetailAPIView.as_view(), name='video_api'),
    path('videos/', VideoListAPIView.as_view(), name='videos_api'),
]

authorisation_user/urls.py
from django.urls import path

from .views import (
    RegistrationView,
    LoginUserView,
    LogoutUserView,
    ProfileView,
    FollowAndUnfollowView,
    SubscriptionsView,
    ChangeProfileView,
    ChangePasswordView,
    RedirectProfileView,
    UserPopupView,
    HistoryView,
    DeleteVideoFromHistoryView,
    ResetPasswordView,
    ResetPasswordConfirmView,
    ActivationView,
    SendMailAboutActivationView,
)

app_name = 'accounts'
urlpatterns = [
    path('activation/send-mail/again/', SendMailAboutActivationView.as_view(), name='send_mail_about_activation'),
    path('activation/<str:username>/', ActivationView.as_view(), name='activate'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('profile/', RedirectProfileView.as_view(), name='profile_redirect'),
    path('profile/reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password_reset_confirm'),
    path('profile/reset/', ResetPasswordView.as_view(), name='reset_password'),
    path('profile/change/password/', ChangePasswordView.as_view(), name='password_change'),
    path('profile/change/', ChangeProfileView.as_view(), name='profile_change'),
    path('profile/<str:username>/popup/', UserPopupView.as_view(), name='user_popup'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('profile/<str:act>/<str:username>/', FollowAndUnfollowView.as_view(), name='act_profile'),
    path('subscriptions/', SubscriptionsView.as_view(), name='subscriptions'),
    path('history/delete/<str:slug>/', DeleteVideoFromHistoryView.as_view(), name='delete_from_history'),
    path('history/', HistoryView.as_view(), name='history'),
]

django_video_hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('authorisation_user.urls')),
    path('comments/', include('comments.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import (
    BaseView,
    VideoDetailView,
    VideoStreamingResponse,
    CategoryDetailView,
    AddVideoView,
    EditVideoView,
    LikeOrDislikeView,
    VideoForSearchView,
)

app_name = 'main'
urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('video/edit/<str:slug>/', EditVideoView.as_view(), name='edit_video'),
    path('video/add/', AddVideoView.as_view(), name='add_video'),
    path('video/<str:slug>/', VideoDetailView.as_view(), name='video_detail'),
    path('video/streaming/<str:slug>/', VideoStreamingResponse.as_view(), name='video_streaming'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('likes-or-dislikes/<str:slug>/', LikeOrDislikeView.as_view(), name='likes_or_dislikes'),
    path('videos/search/', VideoForSearchView.as_view(), name='search_videos'),
]

main/models.py
from django.db import models
from django.urls import reverse

from .utilities import get_timestamp_path


class Category(models.Model):
    """ Category """

    name = models.CharField(max_length=255, verbose_name='Name')
    slug = models.SlugField(unique=True, verbose_name='Slug')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['name']


class Video(models.Model):
    """ Video """

    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Category', related_name='videos')
    title = models.CharField(max_length=255, verbose_name='Title')
    slug = models.SlugField(unique=True, verbose_name='Slug')
    description = models.TextField(verbose_name='Description')
    author = models.ForeignKey('authorisation_user.AdvUser', on_delete=models.CASCADE, verbose_name='Author',
                               related_name='videos')
    file = models.FileField(verbose_name='Video', upload_to=get_timestamp_path)
    blocked = models.BooleanField(default=False, verbose_name='Blocked video')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')
    preview = models.ImageField(verbose_name='Preview', null=True, blank=True, upload_to=get_timestamp_path)
    views = models.BigIntegerField(verbose_name='Views', default=0)
    subscriptions_views = models.BigIntegerField(verbose_name='With subscription views', default=0)
    private = models.BooleanField(default=False, verbose_name='Private video?')
    comments_on = models.BooleanField(default=True, verbose_name='Comments on?')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """ Get absolute url """

        return reverse('main:video_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'
        ordering = ['-created_at']


class LikeOrDislike(models.Model):
    """ Like """

    LIKE = 'like'
    DISLIKE = 'dislike'
    VOTE_CHOICES = (
        ('like', 'Like'),
        ('dislike', 'Dislike')
    )

    vote = models.CharField(max_length=10, verbose_name='Vote', choices=VOTE_CHOICES)
    video = models.ForeignKey(Video, verbose_name='Video', on_delete=models.CASCADE, related_name='votes')
    user = models.ForeignKey('authorisation_user.AdvUser', verbose_name='User', on_delete=models.CASCADE,
                             related_name='vote')

    def __str__(self):
        return f'{self.user.username} - {self.vote}'

    class Meta:
        verbose_name = 'Like or Dislike'
        verbose_name_plural = 'Likes or Dislikes'

main/forms.py
from django import forms

from .models import Video


class AddVideoForm(forms.ModelForm):
    """ Add video """

    preview = forms.FileField(widget=forms.FileInput, label='Preview', required=True)
    file = forms.FileField(widget=forms.FileInput, label='Video')

    class Meta:
        model = Video
        fields = ('category', 'title', 'slug', 'description', 'preview', 'file', 'private', 'comments_on')


class EditVideoForm(forms.ModelForm):
    """ Edit video """

    preview = forms.FileField(widget=forms.FileInput, label='Preview', required=True)
    file = forms.FileField(widget=forms.FileInput, label='Video')

    class Meta:
        model = Video
        fields = ('category', 'title', 'slug', 'description', 'preview', 'file', 'private', 'comments_on')

main/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import FileResponse, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import UpdateView

from .models import Video, Category, LikeOrDislike
from .forms import AddVideoForm, EditVideoForm
from .send_mail import send_manager_about_new_video
from .utilities import ranged
from comments.utils import create_comments_tree
from comments.forms import CommentForm


class BaseView(ListView):
    """ Home """

    model = Video
    template_name = 'base.html'


class CategoryDetailView(DetailView):
    """ Category Detail """

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'main/category_detail.html'
    slug_url_kwarg = 'slug'


class VideoDetailView(DetailView):
    """ Detail video """

    model = Video
    queryset = Video.objects.all()
    context_object_name = 'video'
    template_name = 'main/video_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        comments = kwargs['object'].comments.all()
        result = create_comments_tree(comments)
        comment_form = CommentForm()
        context = super().get_context_data(**kwargs)
        context['comments'] = result
        context['comment_form'] = comment_form
        return context

    def get(self, request, *args, **kwargs):
        video = Video.objects.get(slug=kwargs['slug'])
        if video.private and video.author != request.user:
            raise HttpResponseForbidden('The author has hidden this video or it has been deleted!')
        elif video.blocked:
            raise HttpResponseForbidden('This video was blocked by moderation!')
        return super().get(request, *args, **kwargs)


class VideoStreamingResponse(View):
    """ Video player (chunked video upload) """

    def get(self, request, *args, **kwargs):
        video = Video.objects.get(slug=kwargs['slug'])
        video.views += 1
        if request.user.is_authenticated:
            video.subscriptions_views += 1
            request.user.history.add(video)
            request.user.save()
        video.save()
        file = open(video.file.path, 'rb')
        file_size = video.file.size
        content_length = file_size
        content_range = request.headers.get('range')
        headers = {}
        # Search start and end position
        if content_range is not None:
            content_range = content_range.strip().lower()
            content_ranges = content_range.split('=')[-1]
            range_start, range_end, *_ = map(str.strip, (content_ranges + '-').split('-'))
            range_start = max(0, int(range_start)) if range_start else 0
            range_end = min(file_size - 1, int(range_end)) if range_end else file_size - 1
            content_length = (range_end - range_start) + 1
            file = ranged(file, start=range_start, end=range_end + 1)
            headers = {'Content-Range': f'bytes {range_start}-{range_end}/{file_size}'}
        response = FileResponse(file)
        response.set_headers({
            'Accept-Ranges': 'bytes',
            'Content-Length': str(content_length),
            **headers,
        })
        return response


class AddVideoView(LoginRequiredMixin, View):
    """ Add video """

    def dispatch(self, request, *args, **kwargs):
        if not request.user.activated:
            raise HttpResponseForbidden('Your account is not activated!')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = AddVideoForm(request.POST or None)
        context = {'form': form}
        return render(request, 'main/add_video.html', context)

    def post(self, request, *args, **kwargs):
        form = AddVideoForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            new_video = form.save(commit=False)
            new_video.category = form.cleaned_data['category']
            new_video.title = form.cleaned_data['title']
            new_video.slug = form.cleaned_data['slug']
            new_video.description = form.cleaned_data['description']
            new_video.preview = form.cleaned_data['preview']
            new_video.file = form.cleaned_data['file']
            new_video.private = form.cleaned_data['private']
            new_video.comments_on = form.cleaned_data['comments_on']
            new_video.author = request.user
            new_video.save()
            send_manager_about_new_video(new_video)
            messages.add_message(request, messages.SUCCESS, 'You are new video has been added!')
            return redirect('main:video_detail', slug=new_video.slug)
        context = {'form': form}
        return render(request, 'main/add_video.html', context)


class EditVideoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """ Edit video """

    model = Video
    template_name = 'main/edit_video.html'
    form_class = EditVideoForm
    slug_url_kwarg = 'slug'
    success_message = 'You are video has been edited!'


class LikeOrDislikeView(LoginRequiredMixin, View):
    """ Likes and Dislikes """

    def post(self, request, *args, **kwargs):
        slug = kwargs['slug']
        video = Video.objects.get(slug=slug)
        act = request.POST.get('act')
        user = request.user
        vote, created = LikeOrDislike.objects.get_or_create(user=user, video=video)
        vote.vote = act
        vote.save()
        return redirect('main:video_detail', slug=slug)


class VideoForSearchView(View):
    """ Video for search """

    def get(self, request, *args, **kwargs):
        query = request.GET.get('search')
        if not query:
            videos = Video.objects.all()
        else:
            videos = Video.objects.filter(Q(title__icontains=query)) or \
                     Video.objects.filter(Q(author__username__icontains=query))
        context = {'video_list': videos}
        return render(request, 'base.html', context)

main/templates/_video.html
{% load video %}
<div class="row">
    <video class="video" controls preload="none" poster="{{ video.preview.url }}">
        <source src="{% url 'main:video_streaming' slug=video.slug %}" type="video/mp4">
    </video>

    <div class="col text-center">
        Author: <br> <img class="img-80 img-fluid" src="{{ video.author.avatar.url }}" alt="">
        <a href="{% url 'accounts:profile' username=video.author.username %}">{{ video.author.username }}</a>
        {% if video.private %}<span class="badge rounded-pill bg-danger">Video private</span>{% endif %}
        {% if video.blocked %}<span class="badge rounded-pill bg-danger">Video blocked</span>{% endif %}
    </div>

    <div class="col text-center">
        Category: <br> <a href="{% url 'main:category_detail' slug=video.category.slug %}">{{ video.category.name }}</a>
        <span class="badge rounded-pill bg-secondary">{{ video.category.videos|filter_video_count }}</span>
    </div>

    {% if user == video.author %}
        <a class="mt-2 btn btn-primary" href="{% url 'main:edit_video' slug=video.slug %}">Edit</a>
    {% endif %}

    <div class="right">{{ video.created_at }}</div>
    <div class="col-2">
        <form class="act" action="{% url 'main:likes_or_dislikes' slug=video.slug %}" method="post">
            {% csrf_token %}
            {% if user.is_authenticated %}
                {% get_vote_user user=user video=video as vote %}
            {% endif %}
            <label for="like_id">
                👍 <span class="badge rounded-pill {% if vote == 'like' %}bg-danger{% else %}bg-secondary{% endif %}">
                        {% likes_or_dislikes_count video=video vote='like' %}
                   </span>
            </label>
            <input id="like_id" class="like_or_dislike radio" type="radio" name="act" value="like">
            <label for="dislike_id">
                👎 <span class="badge rounded-pill {% if vote == 'dislike' %}bg-danger{% else %}bg-secondary{% endif %}">
                        {% likes_or_dislikes_count video=video vote='dislike' %}
                   </span>
            </label>
            <input id="dislike_id" class="like_or_dislike radio" type="radio" name="act" value="dislike">
        </form>
    </div>

    <div class="col-2">Views: <span class="badge rounded-pill bg-secondary">{{ video.views }}</span></div>

</div>

<div class="row">
    <p class="h3 text-center">{{ video.title }}</p>
    <p class="mt-2">Description:</p>
    <div class="margin-left"><p>{{ video.description }}</p></div>
</div>

main/templates/_video_poster.html
<div class="card pb-2 h-100">
    <a href="{% url 'main:video_detail' slug=video.slug %}"><img class="card-img-top" src="{{ video.preview.url }}" alt=""></a>
    <div class="card-body">
        <a class="card-title h5" href="{% url 'main:video_detail' slug=video.slug %}">{{ video.title }}</a>
        {% if video.private %}<span class="badge rounded-pill bg-danger">Video private</span>{% endif %}
        {% if video.blocked %}<span class="badge rounded-pill bg-danger">Video blocked</span>{% endif %}
    </div>
    <ul class="list-group">
        <li class="list-group-item">
            <span class="user_popup">
                <img class="img-80 img-fluid" src="{{ video.author.avatar.url }}" alt="">
                <a class="h5" href="{% url 'accounts:profile' username=video.author.username %}">{{ video.author }}</a>
            </span>
        </li>
        <li class="right list-group-item">{{ video.created_at }}</li>
        <li class="right list-group-item">Views:  <span class="badge rounded-pill bg-secondary">{{ video.views }}</span></li>
    </ul>
</div>

main/templates/base.html
{% load static %}
{% load video %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Home{% endblock title %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    </head>
    <body>

        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock navbar %}

        <!-- Messages -->
        <div class="container">
            <div class="row">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert {% if message.level == 20 %}alert-info{% elif message.level == 30 %}alert-warning{% elif message.level == 40 %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>

            <!-- Content -->
            {% block content %}
                <div class="row mb-2">
                    <form action="{% url 'main:search_videos' %}" method="get">
                        <label for="search_id">Search</label>
                        <input id="search_id" class="form-control me-2 text-center search" name="search" type="search"
                               placeholder="Search video">
                        <button class="btn btn-outline-success mt-1" type="submit">Search</button>
                    </form>
                </div>
                <div class="row">
                    {% filter_private_videos videos=video_list as videos %}
                    {% for video in videos %}
                        <div class="col-md-3">
                            {% include '_video_poster.html' %}
                        </div>
                    {% endfor %}
                </div>
            {% endblock content %}
        </div>

        {% block footer %}
            {% include 'footer.html' %}
        {% endblock footer %}

        {% block scripts %}
            <!-- Scripts -->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
                    crossorigin="anonymous"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            <script src="{% static 'user_popup.js' %}"></script>
            <script src="{% static 'like_or_dislike.js' %}"></script>
            <script src="{% static 'comments_tree.js' %}"></script>
        {% endblock scripts %}

    </body>
</html>

main/templates/footer.html
<!-- Footer -->
<footer class="mt-5 py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-light">Copyright &copy; Anti YouTube 2021</p>
    </div>
</footer>

main/templates/navbar.html
{% load video %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark text-light bg-dark mb-2">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'main:base' %}">Django 3 Anti YouTube</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item active"><a class="nav-link" href="{% url 'main:base' %}"
                                               aria-current="page">Home</a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:subscriptions' %}">Subscriptions</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'main:category_detail' slug=category.slug %}">{{ category.name }} <span
                                    class="badge rounded-pill bg-secondary">{{ category.videos|filter_video_count }}</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="accountDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Account</a>
                    <ul class="dropdown-menu" aria-labelledby="accountDropdown">
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'accounts:history' %}">History</a></li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:profile' username=user.username %}">Profile</a>
                            </li>
                            {% if not user.activated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:send_mail_about_activation' %}">Again send mail about activation</a></li>
                            {% endif %}
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:profile_change' %}">Edit Profile</a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change password</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Registration</a></li>
                            <li><a class="dropdown-item" href="{% url 'accounts:reset_password' %}">Reset password</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'main:add_video' %}">Add video</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'api:base_api' %}">API</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

main/templates/video_detail.html
{% extends 'base.html' %}

{% block content %}
    {% include '_video.html' %}
{% endblock content %}